[package]
name = "spop"
version = "0.10.1"
authors = ["Nicolas Embriz <nbari@tequila.io>"]
description = "Library for parsing HAProxy SPOP (Stream Processing Offload Protocol)"
documentation = "https://docs.rs/spop/latest/spop/"
repository = "https://github.com/nbari/spop"
readme = "README.md"
keywords = ["haproxy", "spop", "spoe"]
categories = ["network-programming"]
license = "BSD-3-Clause"
edition = "2024"

[dependencies]
anyhow = "1"
bytes = "1"
futures = "0.3"
nom = "8.0"
rand = "0.9"
semver = "1.0"
thiserror = "2.0"
tokio = { version = "1.44", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }

[lib]
name = "spop"
path = "src/lib.rs"

[[example]]
name = "agent_socket"
path = "examples/agent_socket.rs"

[[example]]
name = "agent_tcp"
path = "examples/agent_tcp.rs"
